[versions]
firebase-web = "9.15.0" # from https://www.npmjs.com/package/firebase
firebase-bindings = "0.1-SNAPSHOT"
kotlin = "1.8.20"
kotlinx-coroutines = "1.6.0"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
